# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd785b4f1908315a1c26e810cac48db5120adfd72f53816e9ca87c371c2bcdd899a742bcaa4856b5782431ecc2023ed51142ce829219d42c57ceef49b1228eb3

test:
  secret_key_base: 1b56132c163c67647699317e65fd2427a7c1813e3f8282808da63cd3d1b27ff226da537aa5758377ccca1914af9816c43870f9b3321c0463067b2216843cfb85

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
